### ISSUE TITLE
continuous action of drone

### ISSUE THREAD

**Issue by xubo92** [KuoHaoZeng/Visual_Reaction#1]
Hi @KuoHaoZeng 

Thanks for sharing the code for this paper! It's a really fun and great application!

I was also using ai2thor and a drone to implement my environment. However, I was not sure how should I enable the continuous action for the drone. From what I see, the ai2thor only provides discrete actions. Could you please give more explanation about this? 

Thanks a lot!

**Comment by KuoHaoZeng** [comment]
Hi @xubo92,

AI2THOW provides continuous actions as well like in [RoboTHOR](https://ai2thor.allenai.org/robothor).
In the drone mode, we have [FlyTo](https://github.com/allenai/ai2thor/blob/5fa8ac5c82594716015931137771cbb7156f5311/unity/Assets/Scripts/DroneFPSAgentController.cs#L389), [FlyAhead](https://github.com/allenai/ai2thor/blob/5fa8ac5c82594716015931137771cbb7156f5311/unity/Assets/Scripts/DroneFPSAgentController.cs#L397), [FlyBack](https://github.com/allenai/ai2thor/blob/5fa8ac5c82594716015931137771cbb7156f5311/unity/Assets/Scripts/DroneFPSAgentController.cs#L403), [FlyLeft](https://github.com/allenai/ai2thor/blob/5fa8ac5c82594716015931137771cbb7156f5311/unity/Assets/Scripts/DroneFPSAgentController.cs#L409), [FlyRight](https://github.com/allenai/ai2thor/blob/5fa8ac5c82594716015931137771cbb7156f5311/unity/Assets/Scripts/DroneFPSAgentController.cs#L415), [FlyUp](https://github.com/allenai/ai2thor/blob/5fa8ac5c82594716015931137771cbb7156f5311/unity/Assets/Scripts/DroneFPSAgentController.cs#L421), and [FlyDown](https://github.com/allenai/ai2thor/blob/5fa8ac5c82594716015931137771cbb7156f5311/unity/Assets/Scripts/DroneFPSAgentController.cs#L429) to control the drone movement.
We can specify either a movement vector in `x`, `y`, `z` or a `moveMagnitude` for continuous control.
You can pass these parameters from a Python client by another key-value pair in the input dict.

Please let me know if you have further questions :))

**Comment by KuoHaoZeng** [comment]
issue closed.
please reopen it if you have further questions!
